In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/campuspulse_akgec_200k.csv")

print(df.shape)
df.head()

(200000, 37)

,complaint_id,complaint_date,complaint_time,complainant_type,department,year_of_study,campus_zone,building,floor,room_lab_no,...,estimated_repair_cost,weather_condition,submission_channel,complaint_status,response_time_hours,resolution_time_hours,maintenance_team,resolution_type,priority,actual_expenditure
0,CP-0000001,2025-10-09,12:49:29,Student,Mechanical Engineering,4.0,Main Gate Zone,EN / EC Block,2,Faculty Room,...,2814,Cloudy,Admin Dashboard,Closed,9.99,12.68,Cleaning & Sanitation,Preventive Maintenance,Medium,7190
1,CP-0000002,2024-01-08,12:21:32,Student,Computer Science and Engineering (Artificial I...,4.0,Administrative Block,CSIT Block,Ground,AIML Lab-2,...,10427,Cloudy,Web Portal,Closed,16.30,14.66,IT Support,Software Fix,Low,23112
2,CP-0000003,2026-07-06,16:44:02,Maintenance Staff,Mechanical Engineering,NaN,Laboratory Zone,NLT Block,1,Classroom-301,...,34833,Rainy,Help Desk,Closed,3.07,23.98,Civil Maintenance,Repaired,Medium,71277
3,CP-0000004,2023-12-17,16:03:21,Student,Electronics and Communication Engineering,1.0,Administrative Block,LT Block,1,Classroom-11,...,2436,Cool,Help Desk,Closed,22.66,14.10,General Maintenance,Replaced,Low,6471
4,CP-0000005,2024-01-23,16:38:57,Administrative Staff,Computer Science and Engineering,NaN,Administrative Block,NLT Block,Ground,Classroom-302,...,16224,Humid,Help Desk,Resolved,5.97,25.78,Network Team,Repaired,High,42486

In [2]:
missing_values = ["", " ", "NA", "N/A", "na", "null", "NULL", "None"]

df = df.replace(missing_values, np.nan)

In [3]:
print("Duplicates:", df.duplicated().sum())

df = df.drop_duplicates()

Duplicates: 0

In [4]:
text_columns = df.select_dtypes(include=["object", "string"]).columns
for column in text_columns:
    df[column] = df[column].str.strip()

In [5]:
df["complaint_date"] = pd.to_datetime(df["complaint_date"], errors="coerce")

df["complaint_time"] = pd.to_datetime(df["complaint_time"], errors="coerce").dt.time

C:\Users\acer\AppData\Local\Temp\ipykernel_12824\1635655127.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["complaint_time"] = pd.to_datetime(df["complaint_time"], errors="coerce").dt.time

In [6]:
numeric_columns = [
    "year_of_study",
    "affected_users",
    "issue_duration_hours",
    "previous_similar_complaints",
    "complaints_last_7_days",
    "complaints_last_30_days",
    "recurrence_count",
    "equipment_age_years",
    "infrastructure_age_years",
    "estimated_repair_cost",
    "response_time_hours",
    "resolution_time_hours",
    "actual_expenditure"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

In [7]:
print(df.shape)
print(df.info())

(200000, 37)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 37 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   complaint_id                 200000 non-null  object
 1   complaint_date               200000 non-null  datetime64[ns]
 2   complaint_time               200000 non-null  object
 3   complainant_type             200000 non-null  object
 4   department                   197521 non-null  object
 5   year_of_study                89366 non-null   float64
 6   campus_zone                  200000 non-null  object
 7   building                     200000 non-null  object
 8   floor                        197785 non-null  object
 9   room_lab_no                  198084 non-null  object
 10  facility_type                198037 non-null  object
 11  class_section                196152 non-null  object
 12  issue_category               200000 non-null  object
 13  issue_subcategory            191602 non-null  object
 14  severity                     200000 non-null  object
 15  affected_users               200000 non-null  int64
 16  issue_duration_hours         191020 non-null  float64
 17  previous_similar_complaints  192032 non-null  float64
 18  complaints_last_7_days       190963 non-null  float64
 19  complaints_last_30_days      189810 non-null  float64
 20  recurrence_count             200000 non-null  int64
 21  equipment_age_years          189777 non-null  float64
 22  infrastructure_age_years     200000 non-null  float64
 23  connectivity_impact          43004 non-null   object
 24  safety_risk                  111704 non-null  object
 25  academic_impact              130036 non-null  object
 26  operational_impact           124160 non-null  object
 27  estimated_repair_cost        200000 non-null  int64
 28  weather_condition            192393 non-null  object
 29  submission_channel           189406 non-null  object
 30  complaint_status             200000 non-null  object
 31  response_time_hours          200000 non-null  float64
 32  resolution_time_hours        200000 non-null  float64
 33  maintenance_team             200000 non-null  object
 34  resolution_type              200000 non-null  object
 35  priority                     200000 non-null  object
 36  actual_expenditure           200000 non-null  int64
dtypes: datetime64[ns](1), float64(9), int64(4), object(23)
memory usage: 56.5+ MB
None

In [8]:
print(df.isnull().sum().sort_values(ascending=False))

connectivity_impact            156996
year_of_study                  110634
safety_risk                     88296
operational_impact              75840
academic_impact                 69964
submission_channel              10594
equipment_age_years             10223
complaints_last_30_days         10190
complaints_last_7_days           9037
issue_duration_hours             8980
issue_subcategory                8398
previous_similar_complaints      7968
weather_condition                7607
class_section                    3848
department                       2479
floor                            2215
facility_type                    1963
room_lab_no                      1916
complaint_time                      0
complaint_date                      0
complaint_id                        0
complainant_type                    0
affected_users                      0
recurrence_count                    0
issue_category                      0
building                            0
campus_zone                         0
severity                            0
infrastructure_age_years            0
estimated_repair_cost               0
complaint_status                    0
response_time_hours                 0
resolution_time_hours               0
maintenance_team                    0
resolution_type                     0
priority                            0
actual_expenditure                  0
dtype: int64

In [9]:
print(df.duplicated().sum())

0

In [10]:
print(df["priority"].value_counts())

priority
Medium      70197
Low         68808
High        42242
Critical    18753
Name: count, dtype: int64

In [11]:
print(df["priority"].isnull().sum())

0

In [12]:
print("Shape:", df.shape)
print("Duplicates:", df.duplicated().sum())
print("Missing values:", df.isnull().sum().sum())

Shape: (200000, 37)
Duplicates: 0
Missing values: 587148

In [13]:
df.head()

,complaint_id,complaint_date,complaint_time,complainant_type,department,year_of_study,campus_zone,building,floor,room_lab_no,...,estimated_repair_cost,weather_condition,submission_channel,complaint_status,response_time_hours,resolution_time_hours,maintenance_team,resolution_type,priority,actual_expenditure
0,CP-0000001,2025-10-09,12:49:29,Student,Mechanical Engineering,4.0,Main Gate Zone,EN / EC Block,2,Faculty Room,...,2814,Cloudy,Admin Dashboard,Closed,9.99,12.68,Cleaning & Sanitation,Preventive Maintenance,Medium,7190
1,CP-0000002,2024-01-08,12:21:32,Student,Computer Science and Engineering (Artificial I...,4.0,Administrative Block,CSIT Block,Ground,AIML Lab-2,...,10427,Cloudy,Web Portal,Closed,16.30,14.66,IT Support,Software Fix,Low,23112
2,CP-0000003,2026-07-06,16:44:02,Maintenance Staff,Mechanical Engineering,NaN,Laboratory Zone,NLT Block,1,Classroom-301,...,34833,Rainy,Help Desk,Closed,3.07,23.98,Civil Maintenance,Repaired,Medium,71277
3,CP-0000004,2023-12-17,16:03:21,Student,Electronics and Communication Engineering,1.0,Administrative Block,LT Block,1,Classroom-11,...,2436,Cool,Help Desk,Closed,22.66,14.10,General Maintenance,Replaced,Low,6471
4,CP-0000005,2024-01-23,16:38:57,Administrative Staff,Computer Science and Engineering,NaN,Administrative Block,NLT Block,Ground,Classroom-302,...,16224,Humid,Help Desk,Resolved,5.97,25.78,Network Team,Repaired,High,42486

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 37 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   complaint_id                 200000 non-null  object
 1   complaint_date               200000 non-null  datetime64[ns]
 2   complaint_time               200000 non-null  object
 3   complainant_type             200000 non-null  object
 4   department                   197521 non-null  object
 5   year_of_study                89366 non-null   float64
 6   campus_zone                  200000 non-null  object
 7   building                     200000 non-null  object
 8   floor                        197785 non-null  object
 9   room_lab_no                  198084 non-null  object
 10  facility_type                198037 non-null  object
 11  class_section                196152 non-null  object
 12  issue_category               200000 non-null  object
 13  issue_subcategory            191602 non-null  object
 14  severity                     200000 non-null  object
 15  affected_users               200000 non-null  int64
 16  issue_duration_hours         191020 non-null  float64
 17  previous_similar_complaints  192032 non-null  float64
 18  complaints_last_7_days       190963 non-null  float64
 19  complaints_last_30_days      189810 non-null  float64
 20  recurrence_count             200000 non-null  int64
 21  equipment_age_years          189777 non-null  float64
 22  infrastructure_age_years     200000 non-null  float64
 23  connectivity_impact          43004 non-null   object
 24  safety_risk                  111704 non-null  object
 25  academic_impact              130036 non-null  object
 26  operational_impact           124160 non-null  object
 27  estimated_repair_cost        200000 non-null  int64
 28  weather_condition            192393 non-null  object
 29  submission_channel           189406 non-null  object
 30  complaint_status             200000 non-null  object
 31  response_time_hours          200000 non-null  float64
 32  resolution_time_hours        200000 non-null  float64
 33  maintenance_team             200000 non-null  object
 34  resolution_type              200000 non-null  object
 35  priority                     200000 non-null  object
 36  actual_expenditure           200000 non-null  int64
dtypes: datetime64[ns](1), float64(9), int64(4), object(23)
memory usage: 56.5+ MB

In [15]:
df.isnull().sum().sort_values(ascending=False)

connectivity_impact            156996
year_of_study                  110634
safety_risk                     88296
operational_impact              75840
academic_impact                 69964
submission_channel              10594
equipment_age_years             10223
complaints_last_30_days         10190
complaints_last_7_days           9037
issue_duration_hours             8980
issue_subcategory                8398
previous_similar_complaints      7968
weather_condition                7607
class_section                    3848
department                       2479
floor                            2215
facility_type                    1963
room_lab_no                      1916
complaint_time                      0
complaint_date                      0
complaint_id                        0
complainant_type                    0
affected_users                      0
recurrence_count                    0
issue_category                      0
building                            0
campus_zone                         0
severity                            0
infrastructure_age_years            0
estimated_repair_cost               0
complaint_status                    0
response_time_hours                 0
resolution_time_hours               0
maintenance_team                    0
resolution_type                     0
priority                            0
actual_expenditure                  0
dtype: int64

In [16]:
from pathlib import Path

output_dir = Path("../data/cleaned")
output_dir.mkdir(parents=True, exist_ok=True)

output_path = output_dir / "campuspulse_akgec_cleaned.csv"

df.to_csv(output_path, index=False)

print(f"Cleaned dataset exported to: {output_path}")
print(f"Shape: {df.shape}")

Cleaned dataset exported to: ..\data\cleaned\campuspulse_akgec_cleaned.csv
Shape: (200000, 37)